spring.config.import=optional:file:.env[.properties]
spring.application.name=jwtDemo

server.port=8081
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

app.razorpay.key-id=${APP_RAZORPAY_KEY_ID}
app.razorpay.key-secret=${APP_RAZORPAY_KEY_SECRET}
app.razorpay.currency=${APP_RAZORPAY_CURRENCY:INR}
